# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'analyze_2.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1196, 756)
        self.gridLayout_3 = QtWidgets.QGridLayout(Form)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.cbAnaSN = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbAnaSN.sizePolicy().hasHeightForWidth())
        self.cbAnaSN.setSizePolicy(sizePolicy)
        self.cbAnaSN.setMinimumSize(QtCore.QSize(300, 0))
        self.cbAnaSN.setObjectName("cbAnaSN")
        self.gridLayout_3.addWidget(self.cbAnaSN, 1, 1, 1, 1)
        self.pbtnAnaBrowse = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbtnAnaBrowse.sizePolicy().hasHeightForWidth())
        self.pbtnAnaBrowse.setSizePolicy(sizePolicy)
        self.pbtnAnaBrowse.setObjectName("pbtnAnaBrowse")
        self.gridLayout_3.addWidget(self.pbtnAnaBrowse, 0, 2, 1, 1)
        self.lbAnaLoadDB = QtWidgets.QLabel(Form)
        self.lbAnaLoadDB.setObjectName("lbAnaLoadDB")
        self.gridLayout_3.addWidget(self.lbAnaLoadDB, 0, 0, 1, 1)
        self.leAnadbFile = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leAnadbFile.sizePolicy().hasHeightForWidth())
        self.leAnadbFile.setSizePolicy(sizePolicy)
        self.leAnadbFile.setMinimumSize(QtCore.QSize(600, 0))
        self.leAnadbFile.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.leAnadbFile.setCursorPosition(0)
        self.leAnadbFile.setPlaceholderText("")
        self.leAnadbFile.setObjectName("leAnadbFile")
        self.gridLayout_3.addWidget(self.leAnadbFile, 0, 1, 1, 1)
        self.lbEAnaSub = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbEAnaSub.sizePolicy().hasHeightForWidth())
        self.lbEAnaSub.setSizePolicy(sizePolicy)
        self.lbEAnaSub.setObjectName("lbEAnaSub")
        self.gridLayout_3.addWidget(self.lbEAnaSub, 1, 0, 1, 1)
        self.tabAnalyz = QtWidgets.QTabWidget(Form)
        self.tabAnalyz.setObjectName("tabAnalyz")
        self.tb1Tbl = QtWidgets.QWidget()
        self.tb1Tbl.setObjectName("tb1Tbl")
        self.gridLayout = QtWidgets.QGridLayout(self.tb1Tbl)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lbAnaUSN = QtWidgets.QLabel(self.tb1Tbl)
        self.lbAnaUSN.setObjectName("lbAnaUSN")
        self.gridLayout.addWidget(self.lbAnaUSN, 2, 3, 1, 1)
        self.leAnaUSN = QtWidgets.QLineEdit(self.tb1Tbl)
        self.leAnaUSN.setObjectName("leAnaUSN")
        self.gridLayout.addWidget(self.leAnaUSN, 2, 4, 1, 1)
        self.lbAnaSelect = QtWidgets.QLabel(self.tb1Tbl)
        self.lbAnaSelect.setObjectName("lbAnaSelect")
        self.gridLayout.addWidget(self.lbAnaSelect, 3, 1, 1, 1)
        self.lbAnaName = QtWidgets.QLabel(self.tb1Tbl)
        self.lbAnaName.setObjectName("lbAnaName")
        self.gridLayout.addWidget(self.lbAnaName, 2, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem, 4, 2, 1, 1)
        self.leAnaName = QtWidgets.QLineEdit(self.tb1Tbl)
        self.leAnaName.setObjectName("leAnaName")
        self.gridLayout.addWidget(self.leAnaName, 2, 2, 1, 1)
        self.cbAnaSelect = QtWidgets.QComboBox(self.tb1Tbl)
        self.cbAnaSelect.setObjectName("cbAnaSelect")
        self.gridLayout.addWidget(self.cbAnaSelect, 3, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 2, 0, 1, 1)
        self.tblAna = QtWidgets.QTableWidget(self.tb1Tbl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tblAna.sizePolicy().hasHeightForWidth())
        self.tblAna.setSizePolicy(sizePolicy)
        self.tblAna.setRowCount(1)
        self.tblAna.setObjectName("tblAna")
        self.tblAna.setColumnCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.tblAna.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblAna.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblAna.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblAna.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblAna.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblAna.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblAna.setHorizontalHeaderItem(5, item)
        self.gridLayout.addWidget(self.tblAna, 0, 0, 1, 13)
        self.tabAnalyz.addTab(self.tb1Tbl, "")
        self.tb2Grp = QtWidgets.QWidget()
        self.tb2Grp.setObjectName("tb2Grp")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tb2Grp)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.cbAnaSelect2 = QtWidgets.QComboBox(self.tb2Grp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbAnaSelect2.sizePolicy().hasHeightForWidth())
        self.cbAnaSelect2.setSizePolicy(sizePolicy)
        self.cbAnaSelect2.setMinimumSize(QtCore.QSize(300, 0))
        self.cbAnaSelect2.setObjectName("cbAnaSelect2")
        self.gridLayout_4.addWidget(self.cbAnaSelect2, 1, 2, 1, 1)
        self.pbtnAnaHist = QtWidgets.QPushButton(self.tb2Grp)
        self.pbtnAnaHist.setObjectName("pbtnAnaHist")
        self.gridLayout_4.addWidget(self.pbtnAnaHist, 1, 3, 1, 1)
        self.lbAnaSelect_2 = QtWidgets.QLabel(self.tb2Grp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbAnaSelect_2.sizePolicy().hasHeightForWidth())
        self.lbAnaSelect_2.setSizePolicy(sizePolicy)
        self.lbAnaSelect_2.setObjectName("lbAnaSelect_2")
        self.gridLayout_4.addWidget(self.lbAnaSelect_2, 1, 1, 1, 1)
        self.pbtnAnaPie = QtWidgets.QPushButton(self.tb2Grp)
        self.pbtnAnaPie.setObjectName("pbtnAnaPie")
        self.gridLayout_4.addWidget(self.pbtnAnaPie, 1, 4, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem2, 1, 0, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.tb2Grp)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout_4.addWidget(self.tableWidget, 0, 0, 1, 7)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_4.addItem(spacerItem3, 2, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem4, 1, 6, 1, 1)
        self.pbtnAnaClose = QtWidgets.QPushButton(self.tb2Grp)
        self.pbtnAnaClose.setObjectName("pbtnAnaClose")
        self.gridLayout_4.addWidget(self.pbtnAnaClose, 1, 5, 1, 1)
        self.tabAnalyz.addTab(self.tb2Grp, "")
        self.tab3Desc = QtWidgets.QWidget()
        self.tab3Desc.setObjectName("tab3Desc")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab3Desc)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem5 = QtWidgets.QSpacerItem(15, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem5, 2, 0, 1, 1)
        self.lbTlStuCnt = QtWidgets.QLabel(self.tab3Desc)
        self.lbTlStuCnt.setObjectName("lbTlStuCnt")
        self.gridLayout_2.addWidget(self.lbTlStuCnt, 0, 4, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.tab3Desc)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 2, 1, 1, 2)
        self.label_6 = QtWidgets.QLabel(self.tab3Desc)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 1, 1, 1, 2)
        self.label_5 = QtWidgets.QLabel(self.tab3Desc)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab3Desc)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 3, 1, 1)
        self.lbTlPass = QtWidgets.QLabel(self.tab3Desc)
        self.lbTlPass.setObjectName("lbTlPass")
        self.gridLayout_2.addWidget(self.lbTlPass, 1, 4, 1, 1)
        self.label = QtWidgets.QLabel(self.tab3Desc)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 1, 1, 2)
        self.label_11 = QtWidgets.QLabel(self.tab3Desc)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 3, 1, 1, 2)
        self.label_17 = QtWidgets.QLabel(self.tab3Desc)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 4, 1, 1, 2)
        self.label_20 = QtWidgets.QLabel(self.tab3Desc)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.gridLayout_2.addWidget(self.label_20, 5, 1, 1, 2)
        self.label_10 = QtWidgets.QLabel(self.tab3Desc)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 3, 3, 1, 1)
        self.lbTlAbsent = QtWidgets.QLabel(self.tab3Desc)
        self.lbTlAbsent.setObjectName("lbTlAbsent")
        self.gridLayout_2.addWidget(self.lbTlAbsent, 3, 4, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.tab3Desc)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 2, 3, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.tab3Desc)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 4, 3, 1, 1)
        self.lbHScore = QtWidgets.QLabel(self.tab3Desc)
        self.lbHScore.setObjectName("lbHScore")
        self.gridLayout_2.addWidget(self.lbHScore, 4, 4, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.tab3Desc)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.gridLayout_2.addWidget(self.label_21, 5, 3, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.tab3Desc)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.gridLayout_2.addWidget(self.label_22, 6, 1, 1, 2)
        self.lbTlFail = QtWidgets.QLabel(self.tab3Desc)
        self.lbTlFail.setObjectName("lbTlFail")
        self.gridLayout_2.addWidget(self.lbTlFail, 2, 4, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.tab3Desc)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.gridLayout_2.addWidget(self.label_23, 6, 3, 1, 1)
        self.lbLScore = QtWidgets.QLabel(self.tab3Desc)
        self.lbLScore.setObjectName("lbLScore")
        self.gridLayout_2.addWidget(self.lbLScore, 5, 4, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.tab3Desc)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 7, 1, 1, 2)
        self.label_13 = QtWidgets.QLabel(self.tab3Desc)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 7, 3, 1, 1)
        self.lbTlAverage = QtWidgets.QLabel(self.tab3Desc)
        self.lbTlAverage.setObjectName("lbTlAverage")
        self.gridLayout_2.addWidget(self.lbTlAverage, 7, 4, 1, 1)
        self.lbTlPassPer = QtWidgets.QLabel(self.tab3Desc)
        self.lbTlPassPer.setObjectName("lbTlPassPer")
        self.gridLayout_2.addWidget(self.lbTlPassPer, 6, 4, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 200, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_2.addItem(spacerItem6, 8, 3, 1, 1)
        self.tabAnalyz.addTab(self.tab3Desc, "")
        self.gridLayout_3.addWidget(self.tabAnalyz, 2, 0, 1, 4)

        self.retranslateUi(Form)
        self.tabAnalyz.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pbtnAnaBrowse.setStatusTip(_translate("Form", "opens file chooser/dialog box"))
        self.pbtnAnaBrowse.setText(_translate("Form", "Browse"))
        self.lbAnaLoadDB.setText(_translate("Form", "Load Data Base :"))
        self.leAnadbFile.setStatusTip(_translate("Form", "select the file to edit"))
        self.lbEAnaSub.setText(_translate("Form", "Subject/Tables :"))
        self.lbAnaUSN.setText(_translate("Form", "By USN:"))
        self.lbAnaSelect.setText(_translate("Form", "Select : "))
        self.lbAnaName.setText(_translate("Form", "Search by Name:"))
        item = self.tblAna.verticalHeaderItem(0)
        item.setText(_translate("Form", "1"))
        item = self.tblAna.horizontalHeaderItem(0)
        item.setText(_translate("Form", "USN"))
        item = self.tblAna.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Name"))
        item = self.tblAna.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Internal"))
        item = self.tblAna.horizontalHeaderItem(3)
        item.setText(_translate("Form", "External"))
        item = self.tblAna.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Total"))
        item = self.tblAna.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Result"))
        self.tabAnalyz.setTabText(self.tabAnalyz.indexOf(self.tb1Tbl), _translate("Form", "Table"))
        self.pbtnAnaHist.setText(_translate("Form", "Histogram"))
        self.lbAnaSelect_2.setText(_translate("Form", "Select : "))
        self.pbtnAnaPie.setText(_translate("Form", "Pie Chart"))
        self.pbtnAnaClose.setText(_translate("Form", "Close Plot"))
        self.tabAnalyz.setTabText(self.tabAnalyz.indexOf(self.tb2Grp), _translate("Form", "Graph"))
        self.lbTlStuCnt.setText(_translate("Form", "0"))
        self.label_8.setText(_translate("Form", "Fail"))
        self.label_6.setText(_translate("Form", "Pass"))
        self.label_5.setText(_translate("Form", ":"))
        self.label_2.setText(_translate("Form", ":"))
        self.lbTlPass.setText(_translate("Form", "0"))
        self.label.setText(_translate("Form", "Total Students"))
        self.label_11.setText(_translate("Form", "Absent"))
        self.label_17.setText(_translate("Form", "Highest Scored"))
        self.label_20.setText(_translate("Form", "Lowest Scored"))
        self.label_10.setText(_translate("Form", ":"))
        self.lbTlAbsent.setText(_translate("Form", "0"))
        self.label_7.setText(_translate("Form", ":"))
        self.label_16.setText(_translate("Form", ":"))
        self.lbHScore.setText(_translate("Form", "0"))
        self.label_21.setText(_translate("Form", ":"))
        self.label_22.setText(_translate("Form", "Pass Percentage"))
        self.lbTlFail.setText(_translate("Form", "0"))
        self.label_23.setText(_translate("Form", ":"))
        self.lbLScore.setText(_translate("Form", "0"))
        self.label_14.setText(_translate("Form", "Subject Average"))
        self.label_13.setText(_translate("Form", ":"))
        self.lbTlAverage.setText(_translate("Form", "0"))
        self.lbTlPassPer.setText(_translate("Form", "0"))
        self.tabAnalyz.setTabText(self.tabAnalyz.indexOf(self.tab3Desc), _translate("Form", "Description"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

