# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'home_test_91.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1350, 956)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setStyleSheet(" .QFrame { background-color: qlineargradient(spread:pad, x1:0.432034, y1:0.75, x2:0.292, y2:0, stop:0.0847458 rgba(61, 61, 61, 228), stop:1 rgba(254, 254, 254, 255)) }\n"
"\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(1350, 839))
        self.centralwidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget.setStyleSheet(".QWidget{background-color:qlineargradient(spread:pad, x1:0.53, y1:0.454409, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"background-image:url(\"C:\\Users\\SYED\\Desktop\\cat.jpg\")}\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame2 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame2.sizePolicy().hasHeightForWidth())
        self.frame2.setSizePolicy(sizePolicy)
        self.frame2.setMinimumSize(QtCore.QSize(0, 30))
        self.frame2.setStyleSheet(" .QFrame { background-color :qlineargradient(spread:pad, x1:1, y1:0.551, x2:1, y2:0, stop:0 rgba(0, 3,5, 255), stop:1 rgba(30,130 , 240, 255)) }")
        self.frame2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame2.setLineWidth(5)
        self.frame2.setMidLineWidth(0)
        self.frame2.setObjectName("frame2")
        self.verticalLayout.addWidget(self.frame2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setSpacing(9)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(90, 0))
        self.frame.setMaximumSize(QtCore.QSize(90, 16777215))
        self.frame.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.btn_home = QtWidgets.QToolButton(self.frame)
        self.btn_home.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_home.setAutoFillBackground(False)
        self.btn_home.setInputMethodHints(QtCore.Qt.ImhNone)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("E:/VTUMarksAnalysis/bin/icon/home.duckduckgo.com.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_home.setIcon(icon)
        self.btn_home.setIconSize(QtCore.QSize(72, 72))
        self.btn_home.setCheckable(True)
        self.btn_home.setChecked(True)
        self.btn_home.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
        self.btn_home.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.btn_home.setAutoRaise(True)
        self.btn_home.setArrowType(QtCore.Qt.NoArrow)
        self.btn_home.setObjectName("btn_home")
        self.verticalLayout_5.addWidget(self.btn_home)
        self.btn_new = QtWidgets.QToolButton(self.frame)
        self.btn_new.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_new.setAutoFillBackground(False)
        self.btn_new.setStyleSheet(".QToolButton{background-image:url(\"C:UsersSYEDDesktopicon.ico\")}")
        self.btn_new.setInputMethodHints(QtCore.Qt.ImhNone)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("E:/VTUMarksAnalysis/bin/icon/new.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_new.setIcon(icon1)
        self.btn_new.setIconSize(QtCore.QSize(72, 72))
        self.btn_new.setCheckable(True)
        self.btn_new.setChecked(False)
        self.btn_new.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
        self.btn_new.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.btn_new.setAutoRaise(True)
        self.btn_new.setArrowType(QtCore.Qt.NoArrow)
        self.btn_new.setObjectName("btn_new")
        self.verticalLayout_5.addWidget(self.btn_new)
        self.btn_analyse = QtWidgets.QToolButton(self.frame)
        self.btn_analyse.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_analyse.setAutoFillBackground(False)
        self.btn_analyse.setInputMethodHints(QtCore.Qt.ImhNone)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("E:/project files/python/qtui-py/icon/bw-analysis.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_analyse.setIcon(icon2)
        self.btn_analyse.setIconSize(QtCore.QSize(72, 72))
        self.btn_analyse.setCheckable(False)
        self.btn_analyse.setChecked(False)
        self.btn_analyse.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
        self.btn_analyse.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.btn_analyse.setAutoRaise(True)
        self.btn_analyse.setArrowType(QtCore.Qt.NoArrow)
        self.btn_analyse.setObjectName("btn_analyse")
        self.verticalLayout_5.addWidget(self.btn_analyse)
        self.btn_setting = QtWidgets.QToolButton(self.frame)
        self.btn_setting.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_setting.setAutoFillBackground(False)
        self.btn_setting.setInputMethodHints(QtCore.Qt.ImhNone)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("E:/project files/python/qtui-py/icon/Settings.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_setting.setIcon(icon3)
        self.btn_setting.setIconSize(QtCore.QSize(72, 72))
        self.btn_setting.setCheckable(False)
        self.btn_setting.setChecked(False)
        self.btn_setting.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
        self.btn_setting.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.btn_setting.setAutoRaise(True)
        self.btn_setting.setArrowType(QtCore.Qt.NoArrow)
        self.btn_setting.setObjectName("btn_setting")
        self.verticalLayout_5.addWidget(self.btn_setting)
        spacerItem = QtWidgets.QSpacerItem(20, 200, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_5.addItem(spacerItem)
        self.horizontalLayout_2.addWidget(self.frame)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setAutoFillBackground(False)
        self.stackedWidget.setStyleSheet(".QStackedWidget{margin:0px;}\n"
".QWidget{\n"
"                \n"
"                background-color:rgb(235, 235, 235)}")
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.stackedWidget.setObjectName("stackedWidget")
        self.stk_home = QtWidgets.QWidget()
        self.stk_home.setToolTip("")
        self.stk_home.setToolTipDuration(1000)
        self.stk_home.setStyleSheet(".QWidget{  \n"
"     border-style:inset;\n"
"      background-image:url(./cat2.jpg);\n"
"     background-repeat:no repeat;\n"
"     background-position:center;\n"
"     background-fill:yes;\n"
"}")
        self.stk_home.setObjectName("stk_home")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.stk_home)
        self.gridLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.hmWeb = QtWebKitWidgets.QWebView(self.stk_home)
        self.hmWeb.setEnabled(True)
        self.hmWeb.setUrl(QtCore.QUrl("about:blank"))
        self.hmWeb.setObjectName("hmWeb")
        self.gridLayout_3.addWidget(self.hmWeb, 2, 0, 1, 3)
        self.hmLbl = QtWidgets.QLabel(self.stk_home)
        self.hmLbl.setObjectName("hmLbl")
        self.gridLayout_3.addWidget(self.hmLbl, 1, 0, 1, 1)
        self.hmbtn = QtWidgets.QPushButton(self.stk_home)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hmbtn.sizePolicy().hasHeightForWidth())
        self.hmbtn.setSizePolicy(sizePolicy)
        self.hmbtn.setMinimumSize(QtCore.QSize(192, 0))
        self.hmbtn.setStyleSheet(".QPushButton {background-color: qlineargradient(spread:pad, x1:1, y1:0.551, x2:1, y2:0, stop:0 rgba(70, 73,75, 255), stop:1 rgba(60,160 , 250, 255));\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-radius: 10px;\n"
"    border-color: grey;\n"
"    font: bold 14px;\n"
"    min-width: 10em;\n"
"    padding: 6px;\n"
"    margin:4px}\n"
".QPushButton:pressed { background-color: qlineargradient(spread:pad, x1:1, y1:0.551, x2:1, y2:0, stop:0 rgba(10, 13,15, 255), stop:1 rgba(20,80 , 180, 255));\n"
"    border-style: inset;\n"
"    border-width: 1px;\n"
"    border-radius: 10px;\n"
"    border-color: black;\n"
"    font: bold 14px;\n"
"    color:grey;\n"
"    min-width: 6em;\n"
"    padding: 6px;}\n"
"")
        self.hmbtn.setDefault(False)
        self.hmbtn.setFlat(False)
        self.hmbtn.setObjectName("hmbtn")
        self.gridLayout_3.addWidget(self.hmbtn, 1, 2, 1, 1)
        self.hmLE = QtWidgets.QLineEdit(self.stk_home)
        self.hmLE.setObjectName("hmLE")
        self.gridLayout_3.addWidget(self.hmLE, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_3.addItem(spacerItem1, 0, 1, 1, 1)
        self.stackedWidget.addWidget(self.stk_home)
        self.stk_new = QtWidgets.QWidget()
        self.stk_new.setStyleSheet("")
        self.stk_new.setObjectName("stk_new")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.stk_new)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(15)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.stk_new)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setMovable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tb_create = QtWidgets.QWidget()
        self.tb_create.setObjectName("tb_create")
        self.gridLayout = QtWidgets.QGridLayout(self.tb_create)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(15)
        self.gridLayout.setVerticalSpacing(20)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem2 = QtWidgets.QSpacerItem(20, 7, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem2, 7, 2, 1, 1)
        self.lbCrtYear = QtWidgets.QLabel(self.tb_create)
        self.lbCrtYear.setStatusTip("")
        self.lbCrtYear.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbCrtYear.setObjectName("lbCrtYear")
        self.gridLayout.addWidget(self.lbCrtYear, 1, 1, 1, 1)
        self.pbtnCrtRm = QtWidgets.QPushButton(self.tb_create)
        self.pbtnCrtRm.setToolTipDuration(1000)
        self.pbtnCrtRm.setObjectName("pbtnCrtRm")
        self.gridLayout.addWidget(self.pbtnCrtRm, 6, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout.addItem(spacerItem3, 4, 3, 1, 1)
        self.lbCrtSub = QtWidgets.QLabel(self.tb_create)
        self.lbCrtSub.setAlignment(QtCore.Qt.AlignCenter)
        self.lbCrtSub.setObjectName("lbCrtSub")
        self.gridLayout.addWidget(self.lbCrtSub, 1, 5, 1, 1)
        self.rbtnCrtCSV = QtWidgets.QRadioButton(self.tb_create)
        self.rbtnCrtCSV.setObjectName("rbtnCrtCSV")
        self.gridLayout.addWidget(self.rbtnCrtCSV, 3, 3, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout.addItem(spacerItem4, 2, 2, 1, 1)
        self.pbtnCrtClr = QtWidgets.QPushButton(self.tb_create)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbtnCrtClr.sizePolicy().hasHeightForWidth())
        self.pbtnCrtClr.setSizePolicy(sizePolicy)
        self.pbtnCrtClr.setObjectName("pbtnCrtClr")
        self.gridLayout.addWidget(self.pbtnCrtClr, 6, 6, 1, 1)
        self.pbtnCrtAdd = QtWidgets.QPushButton(self.tb_create)
        self.pbtnCrtAdd.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pbtnCrtAdd.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pbtnCrtAdd.setAcceptDrops(False)
        self.pbtnCrtAdd.setToolTipDuration(1000)
        self.pbtnCrtAdd.setStatusTip("Add row at the end")
        self.pbtnCrtAdd.setAutoDefault(True)
        self.pbtnCrtAdd.setDefault(False)
        self.pbtnCrtAdd.setFlat(False)
        self.pbtnCrtAdd.setObjectName("pbtnCrtAdd")
        self.gridLayout.addWidget(self.pbtnCrtAdd, 6, 1, 1, 1)
        self.tableWidgetCrt = QtWidgets.QTableWidget(self.tb_create)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidgetCrt.sizePolicy().hasHeightForWidth())
        self.tableWidgetCrt.setSizePolicy(sizePolicy)
        self.tableWidgetCrt.setRowCount(1)
        self.tableWidgetCrt.setObjectName("tableWidgetCrt")
        self.tableWidgetCrt.setColumnCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCrt.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCrt.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCrt.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCrt.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCrt.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCrt.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCrt.setHorizontalHeaderItem(5, item)
        self.gridLayout.addWidget(self.tableWidgetCrt, 5, 1, 1, 7)
        self.sbCrtYear = QtWidgets.QSpinBox(self.tb_create)
        self.sbCrtYear.setMinimum(2000)
        self.sbCrtYear.setMaximum(3000)
        self.sbCrtYear.setSingleStep(1)
        self.sbCrtYear.setDisplayIntegerBase(10)
        self.sbCrtYear.setObjectName("sbCrtYear")
        self.gridLayout.addWidget(self.sbCrtYear, 1, 2, 1, 1)
        self.sbCrtSem = QtWidgets.QSpinBox(self.tb_create)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbCrtSem.sizePolicy().hasHeightForWidth())
        self.sbCrtSem.setSizePolicy(sizePolicy)
        self.sbCrtSem.setMinimum(1)
        self.sbCrtSem.setMaximum(8)
        self.sbCrtSem.setObjectName("sbCrtSem")
        self.gridLayout.addWidget(self.sbCrtSem, 1, 4, 1, 1)
        self.pbtnCrtSave = QtWidgets.QPushButton(self.tb_create)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbtnCrtSave.sizePolicy().hasHeightForWidth())
        self.pbtnCrtSave.setSizePolicy(sizePolicy)
        self.pbtnCrtSave.setObjectName("pbtnCrtSave")
        self.gridLayout.addWidget(self.pbtnCrtSave, 6, 7, 1, 1)
        self.cbCrtSub = QtWidgets.QComboBox(self.tb_create)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbCrtSub.sizePolicy().hasHeightForWidth())
        self.cbCrtSub.setSizePolicy(sizePolicy)
        self.cbCrtSub.setToolTip("")
        self.cbCrtSub.setObjectName("cbCrtSub")
        self.gridLayout.addWidget(self.cbCrtSub, 1, 6, 1, 2)
        self.lbCrtSem = QtWidgets.QLabel(self.tb_create)
        self.lbCrtSem.setAlignment(QtCore.Qt.AlignCenter)
        self.lbCrtSem.setObjectName("lbCrtSem")
        self.gridLayout.addWidget(self.lbCrtSem, 1, 3, 1, 1)
        self.rbtnCrtNewdb = QtWidgets.QRadioButton(self.tb_create)
        self.rbtnCrtNewdb.setChecked(True)
        self.rbtnCrtNewdb.setObjectName("rbtnCrtNewdb")
        self.gridLayout.addWidget(self.rbtnCrtNewdb, 3, 1, 1, 2)
        spacerItem5 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 1, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem6, 0, 3, 1, 1)
        self.tabWidget.addTab(self.tb_create, "")
        self.tb_edit = QtWidgets.QWidget()
        self.tb_edit.setObjectName("tb_edit")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tb_edit)
        self.gridLayout_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem7 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_4.addItem(spacerItem7, 2, 4, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_4.addItem(spacerItem8, 4, 4, 1, 1)
        self.rbtnEdtCpy = QtWidgets.QRadioButton(self.tb_edit)
        self.rbtnEdtCpy.setChecked(True)
        self.rbtnEdtCpy.setObjectName("rbtnEdtCpy")
        self.gridLayout_4.addWidget(self.rbtnEdtCpy, 5, 1, 1, 1)
        self.lbEdtSub = QtWidgets.QLabel(self.tb_edit)
        self.lbEdtSub.setObjectName("lbEdtSub")
        self.gridLayout_4.addWidget(self.lbEdtSub, 3, 1, 1, 1)
        self.pbtnEdtDel = QtWidgets.QPushButton(self.tb_edit)
        self.pbtnEdtDel.setObjectName("pbtnEdtDel")
        self.gridLayout_4.addWidget(self.pbtnEdtDel, 8, 3, 1, 1)
        self.lbEdtLoadDB = QtWidgets.QLabel(self.tb_edit)
        self.lbEdtLoadDB.setObjectName("lbEdtLoadDB")
        self.gridLayout_4.addWidget(self.lbEdtLoadDB, 1, 1, 1, 1)
        self.pbtnEdtClr = QtWidgets.QPushButton(self.tb_edit)
        self.pbtnEdtClr.setObjectName("pbtnEdtClr")
        self.gridLayout_4.addWidget(self.pbtnEdtClr, 8, 6, 1, 1)
        self.cbEdtSN = QtWidgets.QComboBox(self.tb_edit)
        self.cbEdtSN.setObjectName("cbEdtSN")
        self.gridLayout_4.addWidget(self.cbEdtSN, 3, 2, 1, 3)
        self.leEdtdbFile = QtWidgets.QLineEdit(self.tb_edit)
        self.leEdtdbFile.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.leEdtdbFile.setCursorPosition(0)
        self.leEdtdbFile.setObjectName("leEdtdbFile")
        self.gridLayout_4.addWidget(self.leEdtdbFile, 1, 2, 1, 3)
        self.pbtnEdtAdd = QtWidgets.QPushButton(self.tb_edit)
        self.pbtnEdtAdd.setObjectName("pbtnEdtAdd")
        self.gridLayout_4.addWidget(self.pbtnEdtAdd, 8, 1, 1, 1)
        self.pbtnEdtRm = QtWidgets.QPushButton(self.tb_edit)
        self.pbtnEdtRm.setObjectName("pbtnEdtRm")
        self.gridLayout_4.addWidget(self.pbtnEdtRm, 8, 2, 1, 1)
        self.rbtnEdtOrignal = QtWidgets.QRadioButton(self.tb_edit)
        self.rbtnEdtOrignal.setObjectName("rbtnEdtOrignal")
        self.gridLayout_4.addWidget(self.rbtnEdtOrignal, 5, 2, 1, 1)
        self.pbtnEdtReset = QtWidgets.QPushButton(self.tb_edit)
        self.pbtnEdtReset.setObjectName("pbtnEdtReset")
        self.gridLayout_4.addWidget(self.pbtnEdtReset, 8, 5, 1, 1)
        self.pbtnEdtSave = QtWidgets.QPushButton(self.tb_edit)
        self.pbtnEdtSave.setObjectName("pbtnEdtSave")
        self.gridLayout_4.addWidget(self.pbtnEdtSave, 8, 7, 1, 1)
        self.pbtnEdtBrowse = QtWidgets.QPushButton(self.tb_edit)
        self.pbtnEdtBrowse.setObjectName("pbtnEdtBrowse")
        self.gridLayout_4.addWidget(self.pbtnEdtBrowse, 1, 5, 1, 1)
        self.tableWidgetEdt = QtWidgets.QTableWidget(self.tb_edit)
        self.tableWidgetEdt.setRowCount(1)
        self.tableWidgetEdt.setObjectName("tableWidgetEdt")
        self.tableWidgetEdt.setColumnCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetEdt.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetEdt.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetEdt.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetEdt.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetEdt.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetEdt.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetEdt.setHorizontalHeaderItem(5, item)
        self.gridLayout_4.addWidget(self.tableWidgetEdt, 7, 1, 1, 7)
        spacerItem9 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_4.addItem(spacerItem9, 6, 4, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(20, 7, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_4.addItem(spacerItem10, 9, 2, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_4.addItem(spacerItem11, 0, 2, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem12, 5, 0, 1, 1)
        self.tabWidget.addTab(self.tb_edit, "")
        self.tb_scrap = QtWidgets.QWidget()
        self.tb_scrap.setObjectName("tb_scrap")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tb_scrap)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lbScpYear = QtWidgets.QLabel(self.tb_scrap)
        self.lbScpYear.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbScpYear.setObjectName("lbScpYear")
        self.gridLayout_2.addWidget(self.lbScpYear, 1, 1, 1, 1)
        self.spScpSem = QtWidgets.QSpinBox(self.tb_scrap)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spScpSem.sizePolicy().hasHeightForWidth())
        self.spScpSem.setSizePolicy(sizePolicy)
        self.spScpSem.setMinimumSize(QtCore.QSize(165, 0))
        self.spScpSem.setMinimum(1)
        self.spScpSem.setMaximum(8)
        self.spScpSem.setObjectName("spScpSem")
        self.gridLayout_2.addWidget(self.spScpSem, 1, 4, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_2.addItem(spacerItem13, 4, 7, 1, 1)
        self.lbScpURL = QtWidgets.QLabel(self.tb_scrap)
        self.lbScpURL.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbScpURL.setObjectName("lbScpURL")
        self.gridLayout_2.addWidget(self.lbScpURL, 5, 1, 1, 1)
        self.lbScpSem = QtWidgets.QLabel(self.tb_scrap)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbScpSem.sizePolicy().hasHeightForWidth())
        self.lbScpSem.setSizePolicy(sizePolicy)
        self.lbScpSem.setMinimumSize(QtCore.QSize(150, 0))
        self.lbScpSem.setAlignment(QtCore.Qt.AlignCenter)
        self.lbScpSem.setObjectName("lbScpSem")
        self.gridLayout_2.addWidget(self.lbScpSem, 1, 3, 1, 1)
        self.rbtnScpRV = QtWidgets.QRadioButton(self.tb_scrap)
        self.rbtnScpRV.setObjectName("rbtnScpRV")
        self.gridLayout_2.addWidget(self.rbtnScpRV, 3, 3, 1, 1)
        self.leScpURL = QtWidgets.QLineEdit(self.tb_scrap)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leScpURL.sizePolicy().hasHeightForWidth())
        self.leScpURL.setSizePolicy(sizePolicy)
        self.leScpURL.setMinimumSize(QtCore.QSize(642, 25))
        self.leScpURL.setObjectName("leScpURL")
        self.gridLayout_2.addWidget(self.leScpURL, 5, 2, 1, 5)
        self.rbtnScpReg = QtWidgets.QRadioButton(self.tb_scrap)
        self.rbtnScpReg.setChecked(True)
        self.rbtnScpReg.setObjectName("rbtnScpReg")
        self.gridLayout_2.addWidget(self.rbtnScpReg, 3, 1, 1, 1)
        self.pbtnScpLoad = QtWidgets.QPushButton(self.tb_scrap)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbtnScpLoad.sizePolicy().hasHeightForWidth())
        self.pbtnScpLoad.setSizePolicy(sizePolicy)
        self.pbtnScpLoad.setMinimumSize(QtCore.QSize(133, 34))
        self.pbtnScpLoad.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pbtnScpLoad.setStyleSheet(".QPushButton {background-color: qlineargradient(spread:pad, x1:1, y1:0.551, x2:1, y2:0, stop:0 rgba(70, 73,75, 255), stop:1 rgba(50,180 , 255, 255));\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-radius: 10px;\n"
"    border-color: grey;\n"
"    font: bold 14px;\n"
"    min-width: 7em;\n"
"    padding: 6px;}\n"
".QPushButton:pressed { background-color: qlineargradient(spread:pad, x1:1, y1:0.551, x2:1, y2:0, stop:0 rgba(10, 13,15, 255), stop:1 rgba(20,80 , 180, 255));\n"
"    border-style: inset;\n"
"    border-width: 1px;\n"
"    border-radius: 10px;\n"
"    border-color: black;\n"
"    font: bold 14px;\n"
"    color:grey;\n"
"    min-width: 6em;\n"
"    padding: 6px;}\n"
"")
        self.pbtnScpLoad.setAutoDefault(True)
        self.pbtnScpLoad.setDefault(False)
        self.pbtnScpLoad.setFlat(False)
        self.pbtnScpLoad.setObjectName("pbtnScpLoad")
        self.gridLayout_2.addWidget(self.pbtnScpLoad, 5, 7, 1, 1)
        self.lbScpStatus = QtWidgets.QLabel(self.tb_scrap)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbScpStatus.sizePolicy().hasHeightForWidth())
        self.lbScpStatus.setSizePolicy(sizePolicy)
        self.lbScpStatus.setMinimumSize(QtCore.QSize(0, 130))
        font = QtGui.QFont()
        font.setFamily("Arial Unicode MS")
        font.setPointSize(20)
        self.lbScpStatus.setFont(font)
        self.lbScpStatus.setTextFormat(QtCore.Qt.RichText)
        self.lbScpStatus.setAlignment(QtCore.Qt.AlignCenter)
        self.lbScpStatus.setObjectName("lbScpStatus")
        self.gridLayout_2.addWidget(self.lbScpStatus, 8, 3, 1, 3)
        self.lbScpUSN = QtWidgets.QLabel(self.tb_scrap)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbScpUSN.sizePolicy().hasHeightForWidth())
        self.lbScpUSN.setSizePolicy(sizePolicy)
        self.lbScpUSN.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lbScpUSN.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lbScpUSN.setTextFormat(QtCore.Qt.RichText)
        self.lbScpUSN.setAlignment(QtCore.Qt.AlignCenter)
        self.lbScpUSN.setObjectName("lbScpUSN")
        self.gridLayout_2.addWidget(self.lbScpUSN, 1, 5, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_2.addItem(spacerItem14, 2, 7, 1, 1)
        self.leScpUSN = QtWidgets.QLineEdit(self.tb_scrap)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leScpUSN.sizePolicy().hasHeightForWidth())
        self.leScpUSN.setSizePolicy(sizePolicy)
        self.leScpUSN.setObjectName("leScpUSN")
        self.gridLayout_2.addWidget(self.leScpUSN, 1, 6, 1, 1)
        self.line = QtWidgets.QFrame(self.tb_scrap)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 6, 1, 2, 7)
        self.textBrowser = QtWidgets.QTextBrowser(self.tb_scrap)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout_2.addWidget(self.textBrowser, 9, 1, 1, 7)
        self.spScpYear = QtWidgets.QSpinBox(self.tb_scrap)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spScpYear.sizePolicy().hasHeightForWidth())
        self.spScpYear.setSizePolicy(sizePolicy)
        self.spScpYear.setMinimumSize(QtCore.QSize(291, 0))
        self.spScpYear.setMinimum(2000)
        self.spScpYear.setMaximum(3000)
        self.spScpYear.setSingleStep(1)
        self.spScpYear.setDisplayIntegerBase(10)
        self.spScpYear.setObjectName("spScpYear")
        self.gridLayout_2.addWidget(self.spScpYear, 1, 2, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem15, 0, 3, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem16, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tb_scrap, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.stackedWidget.addWidget(self.stk_new)
        self.horizontalLayout_2.addWidget(self.stackedWidget)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1350, 31))
        self.menubar.setStyleSheet("")
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        MainWindow.setMenuBar(self.menubar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setAutoFillBackground(True)
        self.toolBar.setFloatable(True)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionScrap = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("E:/VTUMarksAnalysis/bin/icon/Internet.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionScrap.setIcon(icon4)
        self.actionScrap.setObjectName("actionScrap")
        self.actionD_Settings = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("E:/VTUMarksAnalysis/bin/icon/Settings.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionD_Settings.setIcon(icon5)
        self.actionD_Settings.setObjectName("actionD_Settings")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("E:/project files/python/qtui-py/icon/Help and support.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon6)
        self.actionAbout.setObjectName("actionAbout")
        self.actionDocs = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("E:/project files/python/qtui-py/icon/doc file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDocs.setIcon(icon7)
        self.actionDocs.setObjectName("actionDocs")
        self.actionAnalyse = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("E:/VTUMarksAnalysis/bin/icon/bw-analysis.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAnalyse.setIcon(icon8)
        self.actionAnalyse.setObjectName("actionAnalyse")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionPref = QtWidgets.QAction(MainWindow)
        self.actionPref.setObjectName("actionPref")
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setEnabled(True)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("E:/VTUMarksAnalysis/bin/icon/FolderGrey.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNew.setIcon(icon9)
        self.actionNew.setVisible(True)
        self.actionNew.setIconVisibleInMenu(True)
        self.actionNew.setPriority(QtWidgets.QAction.NormalPriority)
        self.actionNew.setObjectName("actionNew")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionAnalyse)
        self.menuFile.addAction(self.actionScrap)
        self.menuFile.addSeparator()
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionD_Settings)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.toolBar.addAction(self.actionNew)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionScrap)
        self.toolBar.addSeparator()

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(2)
        self.pbtnCrtClr.clicked.connect(self.tableWidgetCrt.clearContents)
        self.pbtnEdtReset.clicked.connect(self.tableWidgetEdt.reset)
        self.pbtnEdtClr.clicked.connect(self.tableWidgetEdt.clearContents)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_home.setToolTip(_translate("MainWindow", "Home"))
        self.btn_home.setStatusTip(_translate("MainWindow", "Home page of the application"))
        self.btn_home.setText(_translate("MainWindow", "Home"))
        self.btn_new.setToolTip(_translate("MainWindow", "New "))
        self.btn_new.setStatusTip(_translate("MainWindow", "create,edit,scrap the marks"))
        self.btn_new.setText(_translate("MainWindow", "New"))
        self.btn_analyse.setToolTip(_translate("MainWindow", "Analyse"))
        self.btn_analyse.setStatusTip(_translate("MainWindow", "analyse the data/marks"))
        self.btn_analyse.setText(_translate("MainWindow", "Analyse"))
        self.btn_setting.setToolTip(_translate("MainWindow", "Settings"))
        self.btn_setting.setStatusTip(_translate("MainWindow", "set the costume settings to default"))
        self.btn_setting.setText(_translate("MainWindow", "Settings"))
        self.stk_home.setStatusTip(_translate("MainWindow", "Home Page"))
        self.hmLbl.setText(_translate("MainWindow", "  Current link :"))
        self.hmbtn.setText(_translate("MainWindow", "Go!"))
        self.tabWidget.setStatusTip(_translate("MainWindow", "Cancels the current download"))
        self.tb_create.setStatusTip(_translate("MainWindow", "create new database file"))
        self.lbCrtYear.setText(_translate("MainWindow", "  year :"))
        self.pbtnCrtRm.setToolTip(_translate("MainWindow", "Remove"))
        self.pbtnCrtRm.setStatusTip(_translate("MainWindow", "removes selected row"))
        self.pbtnCrtRm.setText(_translate("MainWindow", "Remove Row"))
        self.lbCrtSub.setText(_translate("MainWindow", "subject :"))
        self.rbtnCrtCSV.setStatusTip(_translate("MainWindow", "create a new CSV file."))
        self.rbtnCrtCSV.setText(_translate("MainWindow", "save as csv"))
        self.pbtnCrtClr.setStatusTip(_translate("MainWindow", "clears all the contents of the table"))
        self.pbtnCrtClr.setText(_translate("MainWindow", "Clear all"))
        self.pbtnCrtAdd.setToolTip(_translate("MainWindow", "Add", "this is"))
        self.pbtnCrtAdd.setText(_translate("MainWindow", "Add Row"))
        item = self.tableWidgetCrt.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidgetCrt.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "USN"))
        item = self.tableWidgetCrt.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.tableWidgetCrt.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Internal"))
        item = self.tableWidgetCrt.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "External"))
        item = self.tableWidgetCrt.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Total"))
        item = self.tableWidgetCrt.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Result"))
        self.sbCrtYear.setStatusTip(_translate("MainWindow", "select year"))
        self.sbCrtSem.setStatusTip(_translate("MainWindow", "select sem"))
        self.pbtnCrtSave.setToolTip(_translate("MainWindow", "Save"))
        self.pbtnCrtSave.setStatusTip(_translate("MainWindow", "Save the content to selected file format"))
        self.pbtnCrtSave.setText(_translate("MainWindow", "Save"))
        self.cbCrtSub.setStatusTip(_translate("MainWindow", "select subjects"))
        self.lbCrtSem.setText(_translate("MainWindow", "semester :"))
        self.rbtnCrtNewdb.setStatusTip(_translate("MainWindow", "Create a new database file"))
        self.rbtnCrtNewdb.setText(_translate("MainWindow", "New database/Table"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tb_create), _translate("MainWindow", "Create"))
        self.tb_edit.setStatusTip(_translate("MainWindow", "edit database file"))
        self.rbtnEdtCpy.setStatusTip(_translate("MainWindow", "creats a copy of this db file"))
        self.rbtnEdtCpy.setText(_translate("MainWindow", "save as copy"))
        self.lbEdtSub.setText(_translate("MainWindow", "Subject/Tables :"))
        self.pbtnEdtDel.setText(_translate("MainWindow", "Delete/Drop Table"))
        self.lbEdtLoadDB.setText(_translate("MainWindow", "Load Data Base :"))
        self.pbtnEdtClr.setStatusTip(_translate("MainWindow", "clears all the content of the file"))
        self.pbtnEdtClr.setText(_translate("MainWindow", "Clear all"))
        self.leEdtdbFile.setStatusTip(_translate("MainWindow", "select the file to edit"))
        self.pbtnEdtAdd.setStatusTip(_translate("MainWindow", "adds row at the end"))
        self.pbtnEdtAdd.setText(_translate("MainWindow", "Add Row"))
        self.pbtnEdtRm.setStatusTip(_translate("MainWindow", "removes the selected row"))
        self.pbtnEdtRm.setText(_translate("MainWindow", "Remove Row"))
        self.rbtnEdtOrignal.setStatusTip(_translate("MainWindow", "saves to orignal file"))
        self.rbtnEdtOrignal.setText(_translate("MainWindow", "save to orignal file"))
        self.pbtnEdtReset.setStatusTip(_translate("MainWindow", "Reset to orignal contents"))
        self.pbtnEdtReset.setText(_translate("MainWindow", "Reset"))
        self.pbtnEdtSave.setStatusTip(_translate("MainWindow", "Save the content to selected file ."))
        self.pbtnEdtSave.setText(_translate("MainWindow", "Save"))
        self.pbtnEdtBrowse.setStatusTip(_translate("MainWindow", "opens file chooser/dialog box"))
        self.pbtnEdtBrowse.setText(_translate("MainWindow", "Browse"))
        item = self.tableWidgetEdt.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidgetEdt.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "USN"))
        item = self.tableWidgetEdt.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.tableWidgetEdt.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Internal"))
        item = self.tableWidgetEdt.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "External"))
        item = self.tableWidgetEdt.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Total"))
        item = self.tableWidgetEdt.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Result"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tb_edit), _translate("MainWindow", "Edit"))
        self.tb_scrap.setStatusTip(_translate("MainWindow", "get data from server"))
        self.lbScpYear.setText(_translate("MainWindow", "year :"))
        self.lbScpURL.setText(_translate("MainWindow", "Result URL :"))
        self.lbScpSem.setText(_translate("MainWindow", "semester :"))
        self.rbtnScpRV.setStatusTip(_translate("MainWindow", "Scrap for RV student"))
        self.rbtnScpRV.setText(_translate("MainWindow", "RV"))
        self.leScpURL.setStatusTip(_translate("MainWindow", "Plz specify the current url for results"))
        self.leScpURL.setPlaceholderText(_translate("MainWindow", "http://results.vtu.ac.in/results17/result_page.php?usn="))
        self.rbtnScpReg.setStatusTip(_translate("MainWindow", "Scrap for the regular student"))
        self.rbtnScpReg.setText(_translate("MainWindow", "Regular"))
        self.pbtnScpLoad.setStatusTip(_translate("MainWindow", "Starts Scraping"))
        self.pbtnScpLoad.setText(_translate("MainWindow", "Download"))
        self.lbScpStatus.setText(_translate("MainWindow", "Connecting..."))
        self.lbScpUSN.setText(_translate("MainWindow", "starting USN:"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">NOTE:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">    In this section the result from vtu website is fetch and stored it into database.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">    so please specify as above.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">    Semester should not be ignored.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">    please verify before clickling Download button the operation is inevitable.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">    goto Setting window for further options.</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tb_scrap), _translate("MainWindow", "Scrap"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionScrap.setText(_translate("MainWindow", "Scrap"))
        self.actionScrap.setStatusTip(_translate("MainWindow", "collect data from web / from vtu website"))
        self.actionScrap.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.actionD_Settings.setText(_translate("MainWindow", "Default Settings"))
        self.actionD_Settings.setStatusTip(_translate("MainWindow", "set the costume settings to default"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionAbout.setStatusTip(_translate("MainWindow", "about the developers"))
        self.actionAbout.setShortcut(_translate("MainWindow", "F2"))
        self.actionDocs.setText(_translate("MainWindow", "Docs"))
        self.actionDocs.setToolTip(_translate("MainWindow", "Documentation"))
        self.actionDocs.setStatusTip(_translate("MainWindow", "documentation for the application"))
        self.actionDocs.setShortcut(_translate("MainWindow", "F3"))
        self.actionAnalyse.setText(_translate("MainWindow", "Analyse"))
        self.actionAnalyse.setStatusTip(_translate("MainWindow", "analyse the data/marks"))
        self.actionAnalyse.setShortcut(_translate("MainWindow", "F5"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setStatusTip(_translate("MainWindow", "closes the appliction"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionPref.setText(_translate("MainWindow", "Preferenceses"))
        self.actionPref.setStatusTip(_translate("MainWindow", "change the prefrencess"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionNew.setToolTip(_translate("MainWindow", "for new database"))
        self.actionNew.setStatusTip(_translate("MainWindow", "create,edit,scrap the marks"))
        self.actionNew.setShortcut(_translate("MainWindow", "Ctrl+N"))

from PyQt5 import QtWebKitWidgets

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

