# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Setting_tab1.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(889, 494)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tbSet = QtWidgets.QTabWidget(Form)
        self.tbSet.setStyleSheet(".QWidget{\n"
"                \n"
"                background-color:rgb(235, 235, 235)}")
        self.tbSet.setObjectName("tbSet")
        self.tab_M = QtWidgets.QWidget()
        self.tab_M.setObjectName("tab_M")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_M)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.bbxSetM = QtWidgets.QDialogButtonBox(self.tab_M)
        self.bbxSetM.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.bbxSetM.setObjectName("bbxSetM")
        self.gridLayout.addWidget(self.bbxSetM, 5, 2, 1, 2)
        self.lbDBpSetM = QtWidgets.QLabel(self.tab_M)
        self.lbDBpSetM.setObjectName("lbDBpSetM")
        self.gridLayout.addWidget(self.lbDBpSetM, 2, 0, 1, 1)
        self.lbUrlSetM = QtWidgets.QLabel(self.tab_M)
        self.lbUrlSetM.setObjectName("lbUrlSetM")
        self.gridLayout.addWidget(self.lbUrlSetM, 3, 0, 1, 1)
        self.lbScmSetM = QtWidgets.QLabel(self.tab_M)
        self.lbScmSetM.setObjectName("lbScmSetM")
        self.gridLayout.addWidget(self.lbScmSetM, 1, 0, 1, 1)
        self.cbScmSetM = QtWidgets.QComboBox(self.tab_M)
        self.cbScmSetM.setObjectName("cbScmSetM")
        self.gridLayout.addWidget(self.cbScmSetM, 1, 1, 1, 1)
        self.cbBrSetM = QtWidgets.QComboBox(self.tab_M)
        self.cbBrSetM.setObjectName("cbBrSetM")
        self.gridLayout.addWidget(self.cbBrSetM, 0, 1, 1, 1)
        self.leUrlSetM = QtWidgets.QLineEdit(self.tab_M)
        self.leUrlSetM.setObjectName("leUrlSetM")
        self.gridLayout.addWidget(self.leUrlSetM, 3, 1, 1, 1)
        self.leDPSetM = QtWidgets.QLineEdit(self.tab_M)
        self.leDPSetM.setObjectName("leDPSetM")
        self.gridLayout.addWidget(self.leDPSetM, 2, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout.addItem(spacerItem, 4, 2, 1, 1)
        self.pbtnBrwSetM = QtWidgets.QPushButton(self.tab_M)
        self.pbtnBrwSetM.setObjectName("pbtnBrwSetM")
        self.gridLayout.addWidget(self.pbtnBrwSetM, 2, 2, 1, 1)
        self.lbBrnchSetM = QtWidgets.QLabel(self.tab_M)
        self.lbBrnchSetM.setObjectName("lbBrnchSetM")
        self.gridLayout.addWidget(self.lbBrnchSetM, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(7, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 5, 4, 1, 1)
        self.tbSet.addTab(self.tab_M, "")
        self.tab_New = QtWidgets.QWidget()
        self.tab_New.setObjectName("tab_New")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_New)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.bbxSetN = QtWidgets.QDialogButtonBox(self.tab_New)
        self.bbxSetN.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.bbxSetN.setObjectName("bbxSetN")
        self.gridLayout_2.addWidget(self.bbxSetN, 4, 1, 1, 1)
        self.gbSrp = QtWidgets.QGroupBox(self.tab_New)
        self.gbSrp.setObjectName("gbSrp")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gbSrp)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.lburlSrpSN = QtWidgets.QLabel(self.gbSrp)
        self.lburlSrpSN.setObjectName("lburlSrpSN")
        self.gridLayout_5.addWidget(self.lburlSrpSN, 0, 0, 1, 1)
        self.leSrpSN = QtWidgets.QLineEdit(self.gbSrp)
        self.leSrpSN.setText("")
        self.leSrpSN.setObjectName("leSrpSN")
        self.gridLayout_5.addWidget(self.leSrpSN, 0, 1, 1, 2)
        self.lbNSrpSN = QtWidgets.QLabel(self.gbSrp)
        self.lbNSrpSN.setObjectName("lbNSrpSN")
        self.gridLayout_5.addWidget(self.lbNSrpSN, 1, 0, 1, 1)
        self.spSrpSN = QtWidgets.QSpinBox(self.gbSrp)
        self.spSrpSN.setObjectName("spSrpSN")
        self.gridLayout_5.addWidget(self.spSrpSN, 1, 1, 1, 1)
        self.gridLayout_2.addWidget(self.gbSrp, 2, 1, 2, 1)
        self.gbEdt = QtWidgets.QGroupBox(self.tab_New)
        self.gbEdt.setObjectName("gbEdt")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gbEdt)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lbEdtSN = QtWidgets.QLabel(self.gbEdt)
        self.lbEdtSN.setObjectName("lbEdtSN")
        self.gridLayout_4.addWidget(self.lbEdtSN, 0, 0, 1, 1)
        self.leEdtSN = QtWidgets.QLineEdit(self.gbEdt)
        self.leEdtSN.setObjectName("leEdtSN")
        self.gridLayout_4.addWidget(self.leEdtSN, 0, 1, 1, 1)
        self.pbtnEdtSN = QtWidgets.QPushButton(self.gbEdt)
        self.pbtnEdtSN.setObjectName("pbtnEdtSN")
        self.gridLayout_4.addWidget(self.pbtnEdtSN, 0, 2, 1, 1)
        self.chbEdtSN = QtWidgets.QCheckBox(self.gbEdt)
        self.chbEdtSN.setObjectName("chbEdtSN")
        self.gridLayout_4.addWidget(self.chbEdtSN, 1, 0, 1, 2)
        self.gridLayout_2.addWidget(self.gbEdt, 1, 1, 1, 1)
        self.gbCrt = QtWidgets.QGroupBox(self.tab_New)
        self.gbCrt.setObjectName("gbCrt")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gbCrt)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lbCrtSN = QtWidgets.QLabel(self.gbCrt)
        self.lbCrtSN.setObjectName("lbCrtSN")
        self.gridLayout_3.addWidget(self.lbCrtSN, 0, 0, 1, 1)
        self.leCrtSN = QtWidgets.QLineEdit(self.gbCrt)
        self.leCrtSN.setObjectName("leCrtSN")
        self.gridLayout_3.addWidget(self.leCrtSN, 0, 1, 1, 1)
        self.pbtnCrtSN = QtWidgets.QPushButton(self.gbCrt)
        self.pbtnCrtSN.setObjectName("pbtnCrtSN")
        self.gridLayout_3.addWidget(self.pbtnCrtSN, 0, 2, 1, 1)
        self.chbCrtSN = QtWidgets.QCheckBox(self.gbCrt)
        self.chbCrtSN.setObjectName("chbCrtSN")
        self.gridLayout_3.addWidget(self.chbCrtSN, 1, 0, 1, 2)
        self.gridLayout_2.addWidget(self.gbCrt, 0, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem2, 5, 1, 1, 1)
        self.tbSet.addTab(self.tab_New, "")
        self.horizontalLayout.addWidget(self.tbSet)

        self.retranslateUi(Form)
        self.tbSet.setCurrentIndex(0)
        self.pbtnBrwSetM.clicked.connect(self.leDPSetM.clear)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lbDBpSetM.setText(_translate("Form", "Database path :"))
        self.lbUrlSetM.setText(_translate("Form", "Home default URL:"))
        self.lbScmSetM.setText(_translate("Form", "Scheme"))
        self.leUrlSetM.setText(_translate("Form", "http://www.google.co.in/"))
        self.pbtnBrwSetM.setText(_translate("Form", "Browes"))
        self.lbBrnchSetM.setText(_translate("Form", "Branch :"))
        self.tbSet.setTabText(self.tbSet.indexOf(self.tab_M), _translate("Form", "Main"))
        self.gbSrp.setTitle(_translate("Form", "Scrap"))
        self.lburlSrpSN.setText(_translate("Form", "Default URL:"))
        self.lbNSrpSN.setText(_translate("Form", "Number of Students:"))
        self.gbEdt.setTitle(_translate("Form", "Edit"))
        self.lbEdtSN.setText(_translate("Form", "Search path :"))
        self.pbtnEdtSN.setText(_translate("Form", "Browes"))
        self.chbEdtSN.setText(_translate("Form", "Allow save message display"))
        self.gbCrt.setTitle(_translate("Form", "Create"))
        self.lbCrtSN.setText(_translate("Form", "CSV save path :"))
        self.pbtnCrtSN.setText(_translate("Form", "Browes"))
        self.chbCrtSN.setText(_translate("Form", "Allow save message display"))
        self.tbSet.setTabText(self.tbSet.indexOf(self.tab_New), _translate("Form", "New"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

